### ISSUE TITLE
With las-esgf-v8.6.tar.gz datasets not getting displayed

### ISSUE THREAD

**Issue by Akshay-Hegde** [NOAA-PMEL/LAS#1]
With `las-esgf-v8.6.tar.gz` datasets not getting displayed, on `firefox`, but with `chrome` its fine.

**Comment by noaaroland** [comment]
Unless you are installing this on an ESGF compute node using the automated ESGF installation process, do not use this package. It has special configuration and UI elements for ESGF. Please use the standard [release](https://github.com/NOAA-PMEL/LAS/releases/tag/v8.6).
