### ISSUE TITLE
SOCAT: add checkboxes, crossover expocode test-box to QC flagging interface

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1623]
**Reported by @karlmsmith on 30 Jul 2014 03:03 UTC**
To ensure QC procedures are followed and good comments provided, provide a "checklist" for the QC-ers
```
accuracy of fCO2 (A&B: 2; C&D 5; E 10)
following methods / standard operating procedures (A- ?)
metadata complete (A- ?)
data QC acceptable (A- ?)
delta-temperature acceptable (A- ?)
high-quality crossover (A)
```

When boxes are checked, standard text is added to the cruise comment.  For a given flag, the appropriate checkboxes must be checked.  Provide a text box for a crossover, which will also be added as a comment.  If an A cruise, a crossover expocode must be given.

Consideration: make the current comment text box "additional comments", and provide a preview at the bottom that has all the standard comments from the text boxes and expocode with the additional comments appended.  But users might not be happy with the standard comments and will want to tweak them?

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1616

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 30 Jul 2014 03:29 UTC**
(Copying comments from ticket # 1557 so it can be closed out, since it was otherwise complete, and the comment are somewhat applicable to this.)

Note that (as mentioned in other tickets) the Global region flag is intended for cruise region flag conflict resolution and is reserved for regional managers. 

New and Update flags should be reserved for software assignment only (New being the very first flag in each region, Update being the first flag in each region after a data update from the dashboard). Probably use a blank to indicate no flag assignment; just a comment.

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 21 Aug 2014 04:02 UTC**
Updated SOCAT_QC_input.vm checked-in.  After submitting QC the database has the assigned QC flag and comment, and the DSG files have the updated ('Q' - conflict) flag.  However, the flags in the LAS table, even after updating/refreshing.

**Comment by keygen-maker** [comment]
Crossover License Key With Patch for Work, as you will find on Glass door (with a score of 3.3) and on social media, is rated as a leading global employer, a kind of Robin Hoodeska employer linking well-paid American jobs with talented and earning people all around the world.
Kathleen
keygenbro.com
