### ISSUE TITLE
Evaluate Expression does not work if Plus sign in expression

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1701]
**Reported by @AnsleyManke on 22 Dec 2014 18:46 UTC**
This seems to be the same as ticket 636 and #1142.  It occurs in LAS V8. I'm closing those other tickets which refer to other versions of LAS.

Evaluate Expression does not work if there is a plus sign in the expression. The expression in the Help example, converting Celsius to Farenheit, comes through to the Ferret script without the plus sign. $*9/5+32 becomes:

```
 DEFINE SYMBOL ferret_expression = $*9/5   32
```

Other operators, -, /, *, ^  all work fine.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1694

**Comment by noaaroland** [comment]
Fixed in 8.6.9 with special LAS specific encoding for this ferret property.
