### ISSUE TITLE
Misaligned selection when scrolled

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1753]
**Reported by @karlmsmith on 1 Nov 2017 21:43 UTC**
Selecting an area on the main plot when the LAS window is scrolled down does not take into account the scrolling.  Thus the selected area is some distance below the mouse location, depending on how much the LAS window has been scrolled down.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1744

**Comment by noaaroland** [comment]
This is fixed in 8.6.9.
