### ISSUE TITLE
Ferret Scripts: SET VAR/NAME should use uncommon names

### ISSUE THREAD

**Issue by AnsleyManke** [NOAA-PMEL/LAS#1770]

**Comment by AnsleyManke** [comment]
Bryan Littlefield reports to the LAS list that a dataset at NASA,
https://mynasadata.larc.nasa.gov/thredds/dodsC/EarthSystemLAS/hydro/data_https___mynasadata.larc.nasa.gov_thredds_dodsC_ghrsst_sst_agg_sst_k_to_c_analysed_sst.jnl

is hitting an error when requesting to list as CSV.  It tuns out that the dataset uses an init script that converts from temperature in K to C, using a command to rename the variable before the conversion, and then defining the converted variable using the original name:

```
   SET VAR/NAME=($data_($var_num)_var)_in ($data_($var_num)_var)
 !-> SET VAR/NAME=analysed_sst_in analysed_sst

  let/d=1/units="Celsius" analysed_sst = analysed_sst_in - 273
```


That's all fine. We probably provided the folks at NASA this syntax for doing that units conversion.  But then the Ferret script for writing a CSV file use the same "SET VAR/NAME" command, as it needs to redefine the variables as 1-D lists suitable for CSV output. 

The right answer is for the Ferret scripts within LAS to use a renaming that's unlikely to be duplicated by the init scripts that somebody might use,  maybe

`SET VAR/NAME=($data_($var_num)_var)_($session_PID)_csv ($data_($var_num)_var)`

meanwhile, I'll see if Penny can change the syntax in her script a bit so the LAS will work.

**Comment by karlmsmith** [comment]
Picky detail: Celsius = Kelvin - 273.15

**Comment by AnsleyManke** [comment]
that script is part of the NASA LAS config.  I think the underlying data is maybe integer type, but in any case it's up to them.

**Comment by AnsleyManke** [comment]
This is fixed and changes checked in to GitHub. I've tested this for writing single variables to CSV output and when listing a set of 1-D variables as CSV (the UI lets us choose multiple variables for a line plot then write that to CSV).

Init scripts are an older technology, which we'd like to have people replace with F-TDS scripts but they can be handy for some things and MyNasaData servers use them.  Just for reference,

https://ferret.pmel.noaa.gov/LAS/documentation/installer-documentation/advanced-dataset-configuration/copy_of_using-init_scripts-for-custom-ferret-behavior
