### ISSUE TITLE
Print inconsistencies 

### ISSUE THREAD

**Issue by eugeneburger** [NOAA-PMEL/LAS#1774]
Reported by Ansley Manke: 

A problem they've been seeing in the MyNASAdata LAS., https://mynasadata.larc.nasa.gov/EarthSystemLAS/

The sequence is this:
  - plot April data
  - plot October data
  - hit the print button that's BELOW the plot, and the "Print" page
contains the April plot and annotations info. 

It doesn't happen if you use the Print button along the top of the window. 

![LAS_Print_button](https://user-images.githubusercontent.com/16405410/76489541-ee022500-63e5-11ea-82f3-f52584099dfb.png)

**Comment by noaaroland** [comment]
The reason there are print buttons on the output panels as well as the main UI is for the instance that you have more than one panel open. In the case of two panels open, each individual panel print button  makes a page with only that image. I suppose hiding the one in the panel when there is only one panel open might make sense, but I don't like things appearing and disappearing from the interface so I'm inclined to leave the behavior as it is now and just fix the bug.

**Comment by noaaroland** [comment]
I can see in the code where the URL for the old plot might get used for the print button before the new URL is set so I have fixed this potential inconsistency in b46efa65d50bb82b337dff2e521b3bc46a6c3777.

I will make a maintenance release.
