### ISSUE TITLE
missing minimap at top left 

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/LAS#1775]
Hi I just got LAS 8.6.13 installed and I realise the map at the top left is missing. May I know how I can have this fixed?

**Comment by noaaroland** [comment]
Look at the comments in the UI.vm page. The map tiles for the mini-map can come from a variety of sources. All of those sources are volunteer services so some times they go down, but you can change the configuration to try a different source. You'll either need to make a change in the deployed location (which will disappear next time you deploy) or change the file where you un-tarred the distribution and re-deploy.

**Comment by haze1986** [comment]
Hi thanks for the reply but I understand how they can be changed. But the problems is I have verified that the maps are still up. I have tried gebco and OSGEO and getting the same issue. I am not sure if there is something wrong with my config.

**Comment by noaaroland** [comment]
Is the URL of the LAS public? If so I can have a look.

There is nothing to configure for the mini-map except the two lines in the UI.vm, e.g. 

         <meta content="http://www.cmar.csiro.au/geoserver/ows" name="WMS-SERVER" id="wms-server" />
         <meta content="ea-be:World_Bright-Earth-e-Atlas-basemap" name="WMS-LAYER" id="wms-layer" />

 so if those are right the issue likely **not** the LAS installation.

Look on the network tab of the developers tools as the page loads, you should see the mini-map tiles loading from the source when you change the zoom level of the mini-map. E.g.

https://www.cmar.csiro.au/geoserver/ows?FORMAT=image%2Fpng&LAYERS=ea-be%3AWorld_Bright-Earth-e-Atlas-basemap&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&SRS=EPSG%3A4326&BBOX=0,-630,180,-450&WIDTH=256&HEIGHT=256

Verify those requests are happening and the status is 200. That might help you figure out why you aren't seeing any map tiles.
