### ISSUE TITLE
Unable to addxml

### ISSUE THREAD

**Issue by haze1986** [NOAA-PMEL/LAS#1777]
Hi pardon the newbie question but the sources aren't very clear on this. I have searched the directory and only found sample_las.xml. Where should the las.xml be stored so that it can be read by the server? I have tried several locations and my new netcdf data did not appear on the server. I have ran addxml according to the manual and created and updated the las.xml.

Thank you.

**Comment by noaaroland** [comment]
For the record, the documentation is here:

https://ferret.pmel.noaa.gov/LAS/documentation/installer-documentation/adding-gridded-data

To summarize. after you have run the configure script and and answered all the questions, you should find all of your LAS configuration files deployed to the server in the $TOMCAT_HOME/content/las/conf/server directory. And that is the location of the las.xml file to which you add the references to your data set configurations that come from addXML.sh and addDiscrete.sh.
