### ISSUE TITLE
Configuring the 'Constraints' page behavior

### ISSUE THREAD

**Issue by Akshay-Hegde** [NOAA-PMEL/LAS#2]
I see, website is getting updated, so could be the reason some docs I am missing, I was searching for docs for Configuring the 'Constraints' page behavior, it would be helpful for me, time being if you can share docs either pdf or anything, and one more query which I have is I am trying to configure dropdown menu which will have lat and longs like below, so when user selects dropdown say with value `15,90`, I would like to set region `90,90,15,15`  ,  my `ui.xml` file looks like below, where I am trying to keep only view `t, zt` to user, along with  that I would like to disable default `analysis`, I have included `rama_ui.xml#rama` in my dataset, also added in ui.xml but not able to see dropdown menu, can we have dependent dropdown for region also ?  please guide me
 [Here is link to my config files](https://drive.google.com/drive/folders/0B6_-5klDxENTcVNhOUJnUkpaZlU?usp=sharing) 

```
<menu type="constraint" name="rama_buoy_positions"> 
 <item values="15,90">15N, 90E</item> 
 <item values="12,90">12N, 90E</item> 
 <item values="0,90">0, 90E</item> 
 </menu>

<map type="ops" name=rama_ops">
 <ifmenu view="zt" href="#Ops_Std2D_t"/>
 <ifmenu view="t" href="#Ops_Std1D_t"/> 
 <constraint type="variable"/> 
 <constraint type="text" name="location_dropdown"> 
       <menu href="#rama_buoy_positions"/> 
 </constraint>
 </map>

<defaults>
<default name="rama">
   <map href="#rama_ops"/>
 </default>
</defaults>
```

**Comment by noaaroland** [comment]
Not sure exactly where you expect the menu to appear and under what circumstances. And you're probably running to some issues with out of date documentation. That said, you can create [named regions that will show up in the menu for the navigation map](http://ferret.pmel.noaa.gov/LAS/documentation/installer-documentation/advanced-site-configuration/adding-named-regions-to-the-map-widget). They appear when you select the button on the right with the downward pointing chevrons.  That might be easier.

**Comment by Akshay-Hegde** [comment]
@noaaroland  I understood how to setup named region,  but is it possible to project at fixed latitude and longitude by default, when user clicks dataset, as you can see below, By default I would like to show 15N, 90E to user instead, and want to allow user to select only the regions which are listed, rather than allowing user to select anything within bounding box 

```
<menu type="constraint" name="rama_buoy_positions"> 
 <item values="15,90">15N, 90E</item> 
 <item values="12,90">12N, 90E</item> 
 <item values="0,90">0, 90E</item> 
 </menu>
```
By default LAS creates rectangle with available min and max of lat & lon, in current scenario its, 25S - 25N, and  55E-100E, means anything within this bounding box user can select data, 

```
[akshay@localhost tmp]$ f
 	NOAA/PMEL TMAP
 	FERRET v7.1 (optimized)
 	Linux 2.6.32-642.13.1.el6.x86_64 64-bit - 02/15/17
 	12-Jul-17 17:57     

yes? set data "http://las.nio.org/thredds/dodsC/RAMA/daily/sub_temp_sal_dens_cur.nc"
yes? sh d
     currently SET data sets:
    1> http://las.nio.org/thredds/dodsC/RAMA/daily/sub_temp_sal_dens_cur.nc  (default)
 name     title                             I         J         K         L
 T_20     TEMPERATURE (C)long_namet        1:8       1:13      1:29      1:14801
 QT_5020  QUALITY                          1:8       1:13      1:29      1:14801
 ST_6020  SOURCE                           1:8       1:13      1:29      1:14801
 S_41     SALINITY (PSU)                   1:8       1:13      1:29      1:14801
 QS_5041  QUALITY                          1:8       1:13      1:29      1:14801
 SS_6041  SOURCE                           1:8       1:13      1:29      1:14801
 D_71     DENSITY (kg/m**3)                1:8       1:13      1:29      1:14801
 QD_5071  QUALITY                          1:8       1:13      1:29      1:14801
 SD_6071  SOURCE                           1:8       1:13      1:29      1:14801
 U_320    ZONAL CURRENT (C) Tr             1:8       1:13      1:29      1:14801
 V_321    MERID CURRENT (CM/S)             1:8       1:13      1:29      1:14801
 S_300    SPEED (CM/S)                     1:8       1:13      1:29      1:14801
 D_310    DIRECTION (DEG)                  1:8       1:13      1:29      1:14801
 QS_5300  SPEED QUALITY                    1:8       1:13      1:29      1:14801
 QD_5310  DIRECTION QUALITY                1:8       1:13      1:29      1:14801
 SRC_6300 DATA SOURCE                      1:8       1:13      1:29      1:14801
 
yes? sh g t_20
    GRID GFF1
 name       axis              # pts   start                end                 subset
 LON       LONGITUDE            8mi   55E                  100E                full
 LAT       LATITUDE            13 i   25S                  15N                 full
 DEPTH     DEPTH (m)           29 i-  1                    750                 full
 TIME      TIME             14801 r   01-JAN-1977 12:00    10-JUL-2017 12:00   full

``
Also I would like allow user to plot either line plot (t) or Z-time (zt), how to I do that, [Here is link to all my config ](https://drive.google.com/drive/folders/0B6_-5klDxENTcVNhOUJnUkpaZlU?usp=sharing)

**Comment by noaaroland** [comment]
If these data are timeseries at fixed points, or some other time of discrete geometry you should serve them with ERDDAP use the [discrete geometry capabilities](http://ferret.pmel.noaa.gov/LAS/documentation/installer-documentation/adding-scattered-data/dsg-data-served-by-erddap).

**Comment by Akshay-Hegde** [comment]
@noaaroland Yes these data are timeseries (RAMA buoy) at fixed points, but not from ERDDAP, unfortunately these files aggregated in thredds. is it possible to add them without having ERDDAP ?

Here is sample file : https://drive.google.com/open?id=0B6_-5klDxENTSnlyZ1JJS3BMdVk

**Comment by noaaroland** [comment]
Yes, you can add them as degenerate grids, but as you've discovered the UI lacks some obvious features.With data from ERDDAP all of the constraint UI features can be build automatically by software when adding the data set. Features like being able to select individual buoys by name, etc. using ERDDAP is the method we recommend and the only method we currently support for discrete data.

**Comment by Akshay-Hegde** [comment]
@noaaroland , thank you, but one obvious issue which exists is running both ERDDAP and LAS together with same java version, unfortunately Java 1.7 is no longer supported in ERDDAP, requires 1.8 minimum.

**Comment by noaaroland** [comment]
LAS runs fine with Java 8. 7 is the minimum. We routinely run both with 8.
