### ISSUE TITLE
Finish up and publish the "adding scattered data" section.

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#56]
**Reported by @noaaroland on 29 Jun 2007 14:01 UTC**
There's a good start for information on how to add scattered data to Armstrong and V7.0, but it needs to be finished and published in the plone.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/52

**Comment by karlmsmith** [comment]
**Modified by jonathan.s.callahan on 1 Aug 2007 17:40 UTC**

**Comment by karlmsmith** [comment]
**Modified by jonathan.s.callahan on 1 Aug 2007 19:20 UTC**

**Comment by karlmsmith** [comment]
**Comment by jonathan.s.callahan on 2 Aug 2007 18:16 UTC**
The existing documentation is ''good enough'' for an alpha release.

**Comment by haze1986** [comment]
Would a clearer walkthrough on how to add scattered data be published?

**Comment by noaaroland** [comment]
No. Probably not. Use[ LAS 9](https://github.com/NOAA-PMEL/las9) if you're interesting in LAS. Adding scattered data is done there from an admin interface and is entirely automated.

**Comment by haze1986** [comment]
> No. Probably not. Use[ LAS 9](https://github.com/NOAA-PMEL/las9) if you're interesting in LAS. Adding scattered data is done there from an admin interface and is entirely automated.

Thanks Roland, I have just realised that LAS 9 is now the latest, I have now migrated over and it works great. I could get a gridded netcdf data set on it just as before but scattered data from a flexible mesh is still having an error when I add it. Do we need to perform any intermediate steps to get outputs from a flexible mesh simulation (Delft3D-FM) working?

**Comment by noaaroland** [comment]
The definition of "scatter data" in LAS includes only a sub-set of the geometries that are define as [Climate and and Forecast conventions Discrete Sampling Geometries](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/build/ch09.html). The CF DSG data types LAS understands are: point, timeseries, trajectory, and profile.

LAS does not understand mesh data like found in a finite element model. We don't deal with such data sets in our work and it's unlikely LAS will support a "mesh" type scattered data.
